export type {
  RawEAnnotation,
  RawEAttribute,
  RawEClassifier,
  RawEClass,
  RawEcoreDocument,
  RawEDataType,
  RawEEnum,
  RawEEnumLiteral,
  RawEGenericType,
  RawEOperation,
  RawEPackage,
  RawEParameter,
  RawEReference,
  RawEStructuralFeature,
  RawETypeParameter,
  RawUnknownClassifier,
  RawUnknownFeature,
} from './types';
